declare module "magic-string";
declare module "resolve";
declare module "posthtml-parser";
declare module "@babel/traverse";
declare module "@babel/standalone";
declare module "@toypack/resolve";
declare module "postcss";
declare module "postcss-value-parser";
declare module "autoprefixer";
